version: '3'

services:
  php:
    build:
      context: .
      args:
        - uid=${uid}
        - gid=${gid}
    volumes:
      - .:/usr/src/yii2-fias
    ports:
      - '8000:80'
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
    depends_on:
      - mysql
      - fias-stub
  mysql:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: yii2-fias
    ports:
      - '5603:3306'
  fias-stub:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./tests/_fias-stub/html:/var/www/html
    ports:
      - '8001:80'
