#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = \yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/tests/_app/config/common.php',
    require __DIR__ . '/tests/_app/config/console.php'
);

$application = new yii\console\Application($config);
$exitCode    = $application->run();
exit($exitCode);